# Generated by Django 5.1.3 on 2024-12-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_ordermodel_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitemmodel",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
