# Generated by Django 5.1.3 on 2024-12-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_orderitemmodel_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
    ]
