# Generated by Django 5.1.3 on 2024-11-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_rename_product_productmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
