# Generated by Django 5.1.3 on 2024-12-01 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
        ("orders", "0001_initial"),
        ("products", "0003_productmodel_discount_alter_productmodel_price"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductModel",
            new_name="Product",
        ),
    ]
