# Generated by Django 5.1.3 on 2024-12-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_rename_productmodel_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.PositiveIntegerField(
                choices=[
                    (5, 5),
                    (10, 10),
                    (15, 15),
                    (20, 20),
                    (25, 25),
                    (30, 30),
                    (35, 35),
                    (40, 40),
                    (45, 45),
                    (50, 50),
                    (55, 55),
                    (60, 60),
                    (65, 65),
                    (70, 70),
                    (75, 75),
                    (80, 80),
                    (85, 85),
                    (90, 90),
                    (95, 95),
                ],
                default=0,
            ),
        ),
    ]
