# Generated by Django 5.1.3 on 2024-12-01 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
        ("products", "0004_rename_productmodel_product"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CategoryModel",
            new_name="Category",
        ),
    ]
